use_frameworks!

target 'KalturaClient_Example' do
  platform :ios, '10.0'
  pod 'KalturaOttClient', :path => '../KalturaOttClient.podspec'
  
  target 'KalturaClient_Tests' do
    inherit! :search_paths
    
    pod 'KalturaOttClient', :path => '../KalturaOttClient.podspec'
    pod 'Quick', '~> 1.3.2'
    pod 'Nimble', '~> 7.3.3'
  end
end

target 'KalturaClient_Example_macOS' do
  platform :macos, '10.13'
  pod 'KalturaOttClient', :path => '../KalturaOttClient.podspec'
  
  target 'KalturaClient_Example_macOSTests' do
    inherit! :search_paths
    
    pod 'KalturaOttClient', :path => '../KalturaOttClient.podspec'
    pod 'Quick', '~> 1.3.2'
    pod 'Nimble', '~> 7.3.3'
  end
  
end
