language: swift
osx_image: xcode8.3
before_script:
  - pod repo update
script:
  - pod lib lint --fail-fast --verbose
notifications:
  email:
    recipients:
      - moshe.maor@kaltura.com
      - jess.portnoy@kaltura.com
      - Jonathan.Kanarek@kaltura.com
      - nir.belinky@kaltura.com
      - noam.tamim@kaltura.com
    on_success: change
    on_failure: always
