name: Swift Build and Publish

on:
  push:
    branches: '*'

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update pods repo
      run: pod repo update
    - name: Lint
      run: pod lib lint --fail-fast --verbose
