name: Swift Build and Publish

on:
  push:
    branches: '[0-9]+_[0-9]+_[0-9]+'

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Update pods repo
      run: pod repo update
    - name: Tag and Push
      run: |
        chmod +x github-tag-and-push.sh
        GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} ./github-tag-and-push.sh
